{{- if (.Values.keycloak.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "global.fullname" . }}-keycloak
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  clientSecret: {{ .Values.keycloak.clientSecret | b64enc | quote }}
{{- end -}}
